---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: parcel-api-repo

outputs:
  - name: build-output

run:
  path: parcel-api-repo/ci/tasks/build.sh